twig:
    default_path: '%kernel.project_dir%/templates'
    globals: 
        upload_directory: '%assets_upload_directory%'

when@test:
    twig:
        strict_variables: true

# paths:
#     '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator